// Table assumption: load maven_marketing_challenge/silver_layer_marketing_data.csv as table 'Marketing'

// Customers & basics
Total Customers = COUNTROWS(Marketing)

Web Purchases = SUMX(Marketing, VALUE(Marketing[NumWebPurchases]))
Catalog Purchases = SUMX(Marketing, VALUE(Marketing[NumCatalogPurchases]))
Store Purchases = SUMX(Marketing, VALUE(Marketing[NumStorePurchases]))
Total Purchases = [Web Purchases] + [Catalog Purchases] + [Store Purchases]

Web Visits = SUMX(Marketing, VALUE(Marketing[NumWebVisitsMonth]))
Web Conversion Rate = DIVIDE([Web Purchases], [Web Visits])

Total Spend =
    SUMX(Marketing, VALUE(Marketing[MntWines])) +
    SUMX(Marketing, VALUE(Marketing[MntFruits])) +
    SUMX(Marketing, VALUE(Marketing[MntMeatProducts])) +
    SUMX(Marketing, VALUE(Marketing[MntFishProducts])) +
    SUMX(Marketing, VALUE(Marketing[MntSweetProducts])) +
    SUMX(Marketing, VALUE(Marketing[MntGoldProds]))

Avg Income = AVERAGEX(Marketing, VALUE(Marketing[Income]))
Average Age =
    AVERAGEX(Marketing, YEAR(TODAY()) - VALUE(Marketing[Year_Birth]))
Average Tenure (Months) = AVERAGE(Marketing[TenureMonths])

// Product performance
Spend Wines = SUMX(Marketing, VALUE(Marketing[MntWines]))
Spend Fruits = SUMX(Marketing, VALUE(Marketing[MntFruits]))
Spend Meat = SUMX(Marketing, VALUE(Marketing[MntMeatProducts]))
Spend Fish = SUMX(Marketing, VALUE(Marketing[MntFishProducts]))
Spend Sweet = SUMX(Marketing, VALUE(Marketing[MntSweetProducts]))
Spend Gold = SUMX(Marketing, VALUE(Marketing[MntGoldProds]))

Top Product by Spend =
VAR vW = [Spend Wines]
VAR vF = [Spend Fruits]
VAR vM = [Spend Meat]
VAR vFi = [Spend Fish]
VAR vS = [Spend Sweet]
VAR vG = [Spend Gold]
RETURN
    SWITCH(
        TRUE(),
        vW >= vF && vW >= vM && vW >= vFi && vW >= vS && vW >= vG, "Wines",
        vM >= vW && vM >= vF && vM >= vFi && vM >= vS && vM >= vG, "Meat",
        vF >= vW && vF >= vM && vF >= vFi && vF >= vS && vF >= vG, "Fruits",
        vFi >= vW && vFi >= vF && vFi >= vM && vFi >= vS && vFi >= vG, "Fish",
        vS >= vW && vS >= vF && vS >= vM && vS >= vFi && vS >= vG, "Sweet",
        "Gold"
    )

// Campaign success
Accepted Cmp1 Rate = AVERAGE(Marketing[AcceptedCmp1])
Accepted Cmp2 Rate = AVERAGE(Marketing[AcceptedCmp2])
Accepted Cmp3 Rate = AVERAGE(Marketing[AcceptedCmp3])
Accepted Cmp4 Rate = AVERAGE(Marketing[AcceptedCmp4])
Accepted Cmp5 Rate = AVERAGE(Marketing[AcceptedCmp5])
Last Campaign Response Rate = AVERAGE(Marketing[Response])

Best Campaign =
VAR c1 = [Accepted Cmp1 Rate]
VAR c2 = [Accepted Cmp2 Rate]
VAR c3 = [Accepted Cmp3 Rate]
VAR c4 = [Accepted Cmp4 Rate]
VAR c5 = [Accepted Cmp5 Rate]
VAR cr = [Last Campaign Response Rate]
RETURN
    SWITCH(
        TRUE(),
        c1 >= c2 && c1 >= c3 && c1 >= c4 && c1 >= c5 && c1 >= cr, "Campaign 1",
        c2 >= c1 && c2 >= c3 && c2 >= c4 && c2 >= c5 && c2 >= cr, "Campaign 2",
        c3 >= c1 && c3 >= c2 && c3 >= c4 && c3 >= c5 && c3 >= cr, "Campaign 3",
        c4 >= c1 && c4 >= c2 && c4 >= c3 && c4 >= c5 && c4 >= cr, "Campaign 4",
        c5 >= c1 && c5 >= c2 && c5 >= c3 && c5 >= c4 && c5 >= cr, "Campaign 5",
        "Last Campaign"
    )

// Channels underperforming
Store Share = AVERAGEX(Marketing, VALUE(Marketing[Share_Store]))
Catalog Share = AVERAGEX(Marketing, VALUE(Marketing[Share_Catalog]))

Underperforming Channel =
VAR web = [Web Conversion Rate]
VAR store = [Store Share]
VAR c = [Catalog Share]
RETURN
    SWITCH(
        TRUE(),
        web <= store && web <= c, "Web",
        store <= web && store <= c, "Store",
        "Catalog"
    )

// Disconnected dimension for correlation visual (Q1)
DimFactors =
DATATABLE(
    "Factor", STRING,
    "Order", INTEGER,
    {
        { "Web Visits", 1 },
        { "Income", 2 },
        { "Total Spend", 3 }
    }
)

DimChannels = 
DATATABLE(
    "Channel", STRING,
    "Order", INTEGER,
    {
        { "Web", 1 },
        { "Catalog", 2 },
        { "Store", 3 }
    }
)

Correlation Value =
VAR f = SELECTEDVALUE(DimFactors[Factor])
RETURN
    SWITCH(
        TRUE(),
        f = "Web Visits", [Corr(WebPurchases, WebVisits)],
        f = "Income", [Corr(WebPurchases, Income)],
        f = "Total Spend", [Corr(WebPurchases, TotalSpend)],
        BLANK()
    )

// Correlations with Web Purchases (Pearson)
Corr(WebPurchases, WebVisits) =
VAR n = COUNTROWS(Marketing)
VAR sumEX = SUMX(Marketing, VALUE(Marketing[NumWebPurchases]))
VAR sumY = SUMX(Marketing, VALUE(Marketing[NumWebVisitsMonth]))
VAR sumXY = SUMX(Marketing, VALUE(Marketing[NumWebPurchases]) * VALUE(Marketing[NumWebVisitsMonth]))
VAR sumX2 = SUMX(Marketing, VALUE(Marketing[NumWebPurchases]) * VALUE(Marketing[NumWebPurchases]))
VAR sumY2 = SUMX(Marketing, VALUE(Marketing[NumWebVisitsMonth]) * VALUE(Marketing[NumWebVisitsMonth]))
RETURN DIVIDE(
    (n * sumXY) - (sumEX * sumY),
    SQRT( ((n * sumX2) - (sumEX * sumEX)) * ((n * sumY2) - (sumY * sumY)) )
)

Corr(WebPurchases, Income) =
VAR n = COUNTROWS(Marketing)
VAR sumEX = SUMX(Marketing, VALUE(Marketing[NumWebPurchases]))
VAR sumY = SUMX(Marketing, VALUE(Marketing[Income]))
VAR sumXY = SUMX(Marketing, VALUE(Marketing[NumWebPurchases]) * VALUE(Marketing[Income]))
VAR sumX2 = SUMX(Marketing, VALUE(Marketing[NumWebPurchases]) * VALUE(Marketing[NumWebPurchases]))
VAR sumY2 = SUMX(Marketing, VALUE(Marketing[Income]) * VALUE(Marketing[Income]))
RETURN DIVIDE(
    (n * sumXY) - (sumEX * sumY),
    SQRT( ((n * sumX2) - (sumEX * sumEX)) * ((n * sumY2) - (sumY * sumY)) )
)

Corr(WebPurchases, TotalSpend) =
VAR n = COUNTROWS(Marketing)
VAR sumEX = SUMX(Marketing, VALUE(Marketing[NumWebPurchases]))
VAR sumY =
    SUMX(
        Marketing,
        VALUE(Marketing[MntWines]) + VALUE(Marketing[MntFruits]) + VALUE(Marketing[MntMeatProducts]) +
        VALUE(Marketing[MntFishProducts]) + VALUE(Marketing[MntSweetProducts]) + VALUE(Marketing[MntGoldProds])
    )
VAR sumXY =
    SUMX(
        Marketing,
        VALUE(Marketing[NumWebPurchases]) *
        (VALUE(Marketing[MntWines]) + VALUE(Marketing[MntFruits]) + VALUE(Marketing[MntMeatProducts]) +
         VALUE(Marketing[MntFishProducts]) + VALUE(Marketing[MntSweetProducts]) + VALUE(Marketing[MntGoldProds]))
    )
VAR sumX2 = SUMX(Marketing, VALUE(Marketing[NumWebPurchases]) * VALUE(Marketing[NumWebPurchases]))
VAR sumY2 =
    SUMX(
        Marketing,
        VAR t =
            VALUE(Marketing[MntWines]) + VALUE(Marketing[MntFruits]) + VALUE(Marketing[MntMeatProducts]) +
            VALUE(Marketing[MntFishProducts]) + VALUE(Marketing[MntSweetProducts]) + VALUE(Marketing[MntGoldProds])
        RETURN t * t
    )
RETURN DIVIDE(
    (n * sumXY) - (sumEX * sumY),
    SQRT( ((n * sumX2) - (sumEX * sumEX)) * ((n * sumY2) - (sumY * sumY)) )
)