sonar.projectKey=RLopes2327_masters_thesis_rl
sonar.organization=rlopes2327
sonar.sources=.
sonar.exclusions=**/*.pbix, **/*.pbip, **/*.ipynb, **/*.csv, **/*.json, **/*.xml, **/*.yml, **/*.yaml, **/*.md, **/*.txt, **/data/**, **/notebooks/**

sonar.python.coverage.reportPaths=coverage.xml

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=masters_thesis_rl
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8